# Generated by Django 2.2.4 on 2020-03-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_portafolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
